services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
